version: "3"
services:

  web_client:
    container_name: web_client
    build:
      context: ./web_client
      dockerfile: Dockerfile
    volumes:
      - ./web_client:/usr/src/web_client
    ports:
      - 3000:3000
    depends_on:
      - server
    env_file: .env.development
    command: yarn start

  server:
    container_name: server
    build:
      context: ./server
      dockerfile: Dockerfile
    hostname: server
    ports:
      - 8000:8000
    depends_on:
      - postgres
      - redis
    env_file: .env.development
    environment:
      - REDIS_URL=redis://redis

  postgres:
    container_name: postgres
    image: postgres:latest
    hostname: postgres
    ports:
      - 5432:5432

  redis:
    container_name: redis
    image: redis:latest
    hostname: redis
    ports:
      - 6379:6379
