version: "3"
services:

  client:
    container_name: client
    build:
      context: ./client
      dockerfile: Dockerfile
    volumes:
      - ./client:/usr/src/client
    ports:
      - 8080:8080
    depends_on:
      - server
    command: npm run dev

  server: &server
    container_name: server
    build:
      context: ./server
      dockerfile: Dockerfile
    hostname: server
    ports:
      - 8000:8000
    volumes:
      - ./server:/srv/polyledger
    depends_on:
      - postgres
    env_file: .env.development
    command: >
      bash -c '
      python manage.py makemigrations &&
      python manage.py migrate &&
      python manage.py runserver 0.0.0.0:8000'

  postgres:
    container_name: postgres
    image: postgres:latest
    hostname: postgres
    ports:
      - 5432:5432

  redis:
    container_name: redis
    image: redis:latest
    hostname: redis
    ports:
      - 6379:6379

  celery_worker:
    <<: *server
    container_name: celery_worker
    command: celery -A polyledger worker -l info
    depends_on:
      - redis
      - postgres
    ports: []

  celery_beat:
    <<: *server
    container_name: celery_beat
    command: celery -A polyledger beat -l info -s celerybeat-schedule.db
    depends_on:
      - redis
      - postgres
    ports: []
