version: "3"

volumes:
  pgdata:
    driver: local

services:

  nginx:
    container_name: nginx
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    restart: always
    ports:
      - 80:80
    depends_on:
      - server
    command: nginx -g 'daemon off';

  server:
    container_name: server
    build:
      context: ./server
      dockerfile: Dockerfile
    hostname: server
    ports:
      - 8000:8000
    depends_on:
      - postgres
      - redis
    env_file: .env.production

  postgres:
    container_name: postgres
    image: postgres:10.3-alpine
    hostname: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432

  redis:
    container_name: redis
    image: redis:4.0.9-alpine
    hostname: redis
    ports:
      - 6379:6379
