version: "3"

volumes:
  static:

services:

  nginx:
    container_name: nginx
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    image: nginx
    restart: always
    volumes:
      - static:/usr/share/nginx/html/static/admin
      - static:/usr/share/nginx/html/static/rest_framework
    ports:
      - 80:80
    depends_on:
      - server
    command: nginx -g 'daemon off';

  server:
    container_name: server
    build:
      context: ./server
      dockerfile: Dockerfile
    hostname: server
    ports:
      - 8000:8000
    depends_on:
      - postgres
    env_file: .env.production
    command: >
      bash -c '
      python manage.py makemigrations &&
      python manage.py migrate &&
      gunicorn polyledger.wsgi -b 0.0.0.0:8000'

  postgres:
    container_name: postgres
    image: postgres:latest
    hostname: postgres
    ports:
      - 5432:5432

  redis:
    container_name: redis
    image: redis:latest
    hostname: redis
    ports:
      - 6379:6379

  worker:
    container_name: worker
    build:
      context: ./server
    env_file: .env.production
    command: celery -A polyledger worker -l info
    depends_on:
      - server
      - redis
