version: "3"

volumes:
  pgdata:
    driver: local
  static:

services:

  nginx:
    container_name: nginx
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    image: nginx
    restart: always
    volumes:
      - static:/usr/share/nginx/html/static/
    ports:
      - 80:80
    depends_on:
      - server
    command: nginx -g 'daemon off';

  server: &server
    container_name: server
    build:
      context: ./server
      dockerfile: Dockerfile
    hostname: server
    ports:
      - 8000:8000
    depends_on:
      - postgres
    env_file: .env.production
    volumes:
      - static:/usr/share/nginx/html/static/
    command: >
      bash -c '
      python manage.py makemigrations &&
      python manage.py migrate &&
      python manage.py collectstatic --noinput &&
      gunicorn polyledger.wsgi -b 0.0.0.0:8000'

  postgres:
    container_name: postgres
    image: postgres:latest
    hostname: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432

  redis:
    container_name: redis
    image: redis:latest
    hostname: redis
    ports:
      - 6379:6379

  celery_worker:
    <<: *server
    container_name: celery_worker
    hostname: celery_worker
    command: celery -A polyledger worker -l info
    depends_on:
      - redis
      - postgres
    ports: []
    volumes: []

  celery_beat:
    <<: *server
    container_name: celery_beat
    hostname: celery_beat
    command: celery -A polyledger beat -l info -s celerybeat-schedule.db
    depends_on:
      - redis
      - postgres
    ports: []
    volumes: []
